### ISSUE TITLE
Authorization fields in `Configuration` have no effect

### ISSUE THREAD

**Issue by ojacobson** [rivet-gg/Nomad.OAS#3]
STR:

1. Set up a Nomad cluster with ACL enforcement enabled.
2. Create a token with permissions adequate to list jobs. (I used the bootstrap token for this.) Make a note of the secret ID.
3. Set up a request as follows:

    ```rust
    let configuration = Configuration {
      bearer_access_token: Some("your secret ID here".into()),
      ..Configuration::default()
    };

    let jobs = get_jobs(&configuration, None, None, None, None, None).await?;
    println!("{jobs:#?}");
    ```

Expected:

* The program will print a list of jobs, using Rust's default Debug formatter.

Actual:

* Nomad returns a 403 Forbidden response.
* Looking at the HTTP traffic with a proxy, it appears that the token is not actually sent in the request.

A little digging in `jobs_api.rs` suggests that the various auth fields, including `bearer_access_token`, `basic_auth`, `oauth_access_token`, and `api_key` are entirely ignored. Am I missing something?

**Comment by ojacobson** [comment]
It is possible to work around this by customizing the `reqwest::Client` used for the requests. Note that this will blindly send your auth token to anything the client happens to talk to, however, which isn't great if the client is shared with other services or if the URL used isn't carefully controlled:

```rust
        let mut nomad_token_header = HeaderValue::from_str(&self.nomad_token)?;
        nomad_token_header.set_sensitive(true);

        let mut auth_headers = HeaderMap::new();
        auth_headers.append("X-Nomad-Token", nomad_token_header);

        let client = ClientBuilder::new()
            .default_headers(auth_headers)
            .build()?;

        let configuration = Configuration {
            client,
            /* … */
        }
```

**Comment by NathanFlurry** [comment]
Hey @ojacobson! Apologies for the slow response. I'm deprecating this repo in favor of the official Rust client [here](https://github.com/hashicorp/nomad-openapi/tree/main/clients/rust).
