### ISSUE TITLE
`RegisterJobRequest::new` accepts an `Option<Job>` as an argument, and throws it on the floor

### ISSUE THREAD

**Issue by ojacobson** [rivet-gg/Nomad.OAS#4]
Source ref: https://github.com/rivet-gg/Nomad.OAS/blob/master/clients/rust/src/models/register_job_request.rs#L26-L35

The obvious semantics would be that the job is stored in the `job` field, but the actual semantics are that the argument is ignored.

**Comment by NathanFlurry** [comment]
Thanks for the report. I'm deprecating this repo in favor of the official HashiCorp repo [here](https://github.com/hashicorp/nomad-openapi/tree/main/clients/rust).
